### ISSUE TITLE
Catch-all in the middle of a route

### ISSUE THREAD

**Issue by awoimbee** [ibraheemdev/matchit#41]
Hi,
I maintain a project that needs to conform to the docker registry API, that uses catch-all parameters in the middle of routes (see https://github.com/Trow-Registry/trow/issues/352#issuecomment-1731088291, we use axum, which uses matchit).

I wonder how feasible and how much the maintainers of matchit would accept an implementation of cath-all parameters in the middle of routes ?
I think performance would be lower than for standard paths, but I have no idea how the implementation would look like with the radix trie.

Or maybe matchit should be kept lean and we should have a common trait so users can choose their router in axum (to fix https://github.com/tokio-rs/axum/issues/109) ?

**Comment by ibraheemdev** [comment]
See #39. The issue with catch-all routes in the middle of a route is that it makes backtracking quite complicated.For example, if you have `/*blob`, `/*blob/foo/bar`, and `/blog/foo/baz`, how do you match `/x/y/z/foo/x/y/z/foo/baz`? The initial `/foo` in the path doesn't match anything, so after exhausting the first try, you have to go back within the same catch-all segment and try again at different instances of `"/foo"`. And if none of the nested routes match, you have to settle with `/*blob/`. Another example: `/*blob/manifest/:version/x` and `/*blob/tags`, `/blob/manifest/version/tags` initially looks like it matches the first route, but it turns out it matches the second.

I think if we're careful about backtracking then this can be support pretty efficiently in the common case, but it's not trivial.
